# This Cloud Build task runs the deploy to staging.

steps:
  - name: node
    id: 'Install dependencies'
    entrypoint: npm
    args: ['ci']

  - name: node
    id: 'Verify and maybe kick off build for new version'
    entrypoint: bash
    args: ['.cloudbuild/staging-deploy.sh']

  - name: 'gcr.io/$PROJECT_ID/firebase'
    dir: '.cloudbuild/staging/firebase'
    args: ['deploy', '--only', 'hosting']

  - name: 'gcr.io/cloud-builders/gcloud'
    dir: '.cloudbuild/staging/appengine'
    entrypoint: 'bash'
    args: ['-c', 'gcloud app deploy --version hohoho']

options:
  machineType: 'E2_HIGHCPU_32'  # yolo
  env:
  - 'PROJECT_ID=$PROJECT_ID'
  - 'NODE_OPTIONS="--max-old-space-size=32768'
